package ru.maleks.ai_advent_challenge_app.projectfiles

import java.nio.file.Path
import java.time.LocalDate

class ProjectFileAssistant(
    private val tools: ProjectFileTools
) {
    fun execute(goal: String): ProjectTaskResult {
        val normalized = goal.trim().lowercase()
        return when {
            normalized.startsWith("find ") || normalized.startsWith("найди ") -> findUsages(extractArgument(goal))
            "document" in normalized || "документац" in normalized || "readme" in normalized -> updateDocumentation()
            "changelog" in normalized || "изменен" in normalized -> createChangelog()
            "check" in normalized || "проверь" in normalized || "инвариант" in normalized -> checkInvariants()
            else -> ProjectTaskResult(
                summary = "Не понял цель. Примеры: find OllamaClient; обнови документацию; создай changelog; проверь инварианты.",
                inspectedFiles = emptyList()
            )
        }
    }

    private fun findUsages(term: String): ProjectTaskResult {
        val matches = tools.search(term)
        val files = matches.map { it.path }.distinct()
        val report = buildString {
            appendLine("Найдено совпадений: ${matches.size} в ${files.size} файлах.")
            matches.take(40).forEach { appendLine("${it.path}:${it.lineNumber} | ${it.line}") }
            if (matches.size > 40) appendLine("... ещё ${matches.size - 40} совпадений")
        }.trim()
        return ProjectTaskResult(report, files)
    }

    private fun updateDocumentation(): ProjectTaskResult {
        val buildPath = Path.of("build.gradle.kts")
        val sourceFiles = tools.searchableFiles()
            .map(tools::relative)
            .filter { it.toString().endsWith("Cli.kt") }
        val inspected = listOf(buildPath) + sourceFiles
        val gradle = tools.read(buildPath)
        val tasks = Regex("tasks\\.register<JavaExec>\\(\"([^\"]+)\"\\)")
            .findAll(gradle).map { it.groupValues[1] }.toList()
        val cliNames = sourceFiles.map { it.fileName.toString().removeSuffix(".kt") }
        val content = buildString {
            appendLine("# Project assistants")
            appendLine()
            appendLine("Generated by Day 34 Project File Assistant on ${LocalDate.now()}.")
            appendLine()
            appendLine("## Runnable assistants")
            cliNames.sorted().forEach { appendLine("- `${it.removeSuffix("Cli")}`") }
            appendLine()
            appendLine("## Gradle tasks")
            tasks.sorted().forEach { appendLine("- `./gradlew $it --console=plain`") }
            appendLine()
            appendLine("The document is reproducible: run the file assistant and request `обнови документацию`.")
        }
        val change = tools.write(Path.of("docs/generated/project-assistants.md"), content)
        return ProjectTaskResult(
            summary = "Документация обновлена на основе build.gradle.kts и ${sourceFiles.size} CLI-файлов.\n\n${UnifiedDiffFormatter.format(change)}",
            inspectedFiles = inspected,
            changes = listOf(change)
        )
    }

    private fun createChangelog(): ProjectTaskResult {
        val files = tools.searchableFiles().map(tools::relative)
        val relevant = files.filter {
            val text = it.toString().replace('\\', '/')
            text.contains("/developer/") || text.contains("/support/") || text.contains("/projectfiles/")
        }
        val content = buildString {
            appendLine("# AI Advent Challenge changelog")
            appendLine()
            appendLine("## ${LocalDate.now()} — Days 31–34")
            appendLine()
            appendLine("- Developer assistant with project RAG and Git MCP.")
            appendLine("- Automatic AI code review for local changes and pull requests.")
            appendLine("- Support assistant with FAQ RAG and CRM ticket context.")
            appendLine("- Project File Assistant with search, analysis, file creation and invariant checks.")
            appendLine()
            appendLine("### Relevant project files")
            relevant.sorted().take(80).forEach { appendLine("- `$it`") }
        }
        val change = tools.write(Path.of("docs/generated/CHANGELOG_DAY34.md"), content)
        return ProjectTaskResult(
            summary = "Changelog создан после анализа ${relevant.size} файлов.\n\n${UnifiedDiffFormatter.format(change)}",
            inspectedFiles = relevant,
            changes = listOf(change)
        )
    }

    private fun checkInvariants(): ProjectTaskResult {
        val rules = linkedMapOf(
            "TODO" to Regex("\\bTODO\\b"),
            "FIXME" to Regex("\\bFIXME\\b"),
            "println" to Regex("\\bprintln\\s*\\("),
            "hardcoded secret" to Regex("(?i)(password|api[_-]?key|secret)\\s*[=:]\\s*[\"'][^\"']+[\"']")
        )
        val findings = mutableListOf<String>()
        val inspected = tools.searchableFiles().map(tools::relative)
        for ((name, regex) in rules) {
            for (file in inspected) {
                tools.read(file).lineSequence().forEachIndexed { index, line ->
                    if (regex.containsMatchIn(line)) findings += "$name | $file:${index + 1} | ${line.trim()}"
                }
            }
        }
        val report = buildString {
            appendLine("# Project invariant report")
            appendLine()
            appendLine("Checked files: ${inspected.size}")
            appendLine("Findings: ${findings.size}")
            appendLine()
            if (findings.isEmpty()) appendLine("No violations found.") else findings.take(200).forEach { appendLine("- $it") }
        }
        val change = tools.write(Path.of("build/reports/day34-invariants.md"), report)
        return ProjectTaskResult(
            summary = "Проверено ${inspected.size} файлов, найдено ${findings.size} замечаний. Отчёт сохранён в ${change.path}.\n\n${UnifiedDiffFormatter.format(change)}",
            inspectedFiles = inspected,
            changes = listOf(change)
        )
    }

    private fun extractArgument(goal: String): String =
        goal.substringAfter(' ', "").trim().removePrefix("все использования ").removePrefix("использования ").ifBlank { goal }
}
